import type { Metadata } from "next";
import { Inter } from "next/font/google";
// swx@2WS
export const metadata: Metadata = {
  title: "My Home Page",
  description: "Generated by lemi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return ( 
    <>
        {children}  
    </>
    );
}