import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import { Github, Rocket } from "lucide-react";
import { GearIcon, GitHubLogoIcon } from "@radix-ui/react-icons";

const inter = Inter({ subsets: ["latin"] });
// swx@2WS
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-12">
        <aside className="bg-zinc-100 border h-screen lg:col-span-2 rounded-lg">
         <nav className="flex flex-col justify-center mt-10">
         {/* <div className="flex flex-col justify-between ml-2 font-light overflow-" >  */}
          <div className="flex flex-row gap-1"> <h2 className="font-medium">Station</h2></div>
          <div><h2>Department</h2></div>
          <div><h2>Cost Plan</h2></div>
          {/* </div> */}
          </nav> 
      </aside>
      <div className="col-span-10 ">
      <div className="flex flex-row w-full justify-around p-3 m-5 rounded-lg shadow-sm text-black">
        
        <ul className="w-[70%] flex flex-row justify-evenly text-black">
          <li className="hover:text-red-500">
            {" "}
            <Link href="/">Home</Link>
          </li>
          <li className="hover:text-red-500">
            <Link href="/about">About</Link>
          </li>   
          <li className="hover:text-red-500">
            <Link href="/project">Projects</Link>
          </li>
          <li className="hover:text-red-500">
            <Link href="/contact">Contacts</Link>
          </li>
          <li className="hover:text-red-500">
            <Link href="/homepage">homepage</Link>
          </li>
        </ul>
        <div className="w-[15%] ">
          <button className="bg-slate-50 border  text-base text-red-600 px-3 py-1 rounded-lg"><Link href={"/form"}>Get Started</Link></button>
        </div>
        </div>
          {children}
        </div>
        </div>
        <script src="https://unpkg.com/@themesberg/flowbite@1.5.3/dist/flowbite.bundle.js"></script>

        </body>
    </html>
  );
}
